// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZonerDonor.Services;

namespace ZonerDonor.Services.Migrations
{
    [DbContext(typeof(FundContext))]
    partial class FundContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZonerDonor.Core.Models.Donation", b =>
                {
                    b.Property<Guid>("FundraiserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("DonationDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("FundraiserId", "DonorId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            FundraiserId = new Guid("77200551-cd4c-42ea-87e3-c9e87944fa1a"),
                            DonorId = new Guid("e5211cdb-ba2e-4bf6-878a-6cf5fa4816af"),
                            Amount = 40m,
                            DonationDate = new DateTimeOffset(new DateTime(2020, 1, 31, 16, 46, 35, 246, DateTimeKind.Unspecified).AddTicks(4785), new TimeSpan(0, -5, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ZonerDonor.Core.Models.Donor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Donors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5211cdb-ba2e-4bf6-878a-6cf5fa4816af"),
                            CreatedDate = new DateTimeOffset(new DateTime(2020, 1, 1, 16, 46, 35, 237, DateTimeKind.Unspecified).AddTicks(9924), new TimeSpan(0, -5, 0, 0, 0)),
                            Name = "Marcus"
                        });
                });

            modelBuilder.Entity("ZonerDonor.Core.Models.Fundraiser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("CurrentTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fundraisers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77200551-cd4c-42ea-87e3-c9e87944fa1a"),
                            Amount = 10000m,
                            CreatedDate = new DateTimeOffset(new DateTime(2020, 1, 28, 16, 46, 35, 245, DateTimeKind.Unspecified).AddTicks(8730), new TimeSpan(0, -5, 0, 0, 0)),
                            CurrentTotal = 0m,
                            Name = "Pauls Extension"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
